// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Keine allgemeinen Ausnahmetypen abfangen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.initControl(System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.buildList(qs2.core.Enums.eTypList,System.Boolean,System.String,System.String,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Keine allgemeinen Ausnahmetypen abfangen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.CheckElementClassification(qs2.core.vb.dsAdmin.tblSelListEntriesRow,qs2.sitemap.workflowAssist.contListAssistentElem@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Keine allgemeinen Ausnahmetypen abfangen", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.refresControl(qs2.core.Enums.eTypList,System.Boolean,qs2.core.Enums.eStayTyp,System.Boolean,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.loadSelectedProcGroups2(qs2.core.vb.dsObjects.tblStayRow,System.String@,System.Boolean@,System.Collections.Generic.List{System.String}@,qs2.design.auto.ownMCRelationship.eTypAssignments@,System.Boolean,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.elementClick2(qs2.sitemap.workflowAssist.contListAssistentElem,System.Boolean,System.Boolean,System.Boolean,System.String@,System.Boolean@,System.Collections.Generic.List{System.String}@,qs2.design.auto.ownMCRelationship.eTypAssignments@,System.Boolean,System.Boolean,System.Int32,System.Boolean,System.Boolean,System.Boolean)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1303:Literale nicht als lokalisierte Parameter übergeben", Justification = "<Ausstehend>", Scope = "member", Target = "~M:qs2.sitemap.workflowAssist.contListAssistent.doChapters(System.Int32,System.Boolean,System.Boolean,System.Boolean,System.Int32,System.Boolean,System.Collections.Generic.List{qs2.design.auto.workflowAssist.assist.cListAssistentElem}@,System.Collections.Generic.List{qs2.design.auto.workflowAssist.assist.cListAssistentElem}@)")]
