using System;
using System.Collections.Generic;

namespace WCFServicePMDS.Models.DB
{
    public partial class AnamneseOrem
    {
        public AnamneseOrem()
        {
            Pdxanamnese = new HashSet<Pdxanamnese>();
        }

        public Guid Id { get; set; }
        public Guid Idpatient { get; set; }
        public Guid IdbenutzerErstellt { get; set; }
        public DateTime ErstelltAm { get; set; }
        public string DurchgefuehrtMit { get; set; }
        public bool? DepositenJn { get; set; }
        public string Allergie { get; set; }
        public string MobileKrankenpflage { get; set; }
        public string SozialeDienste { get; set; }
        public string VerstaendigungAn { get; set; }
        public string Sonstiges { get; set; }
        public bool? RaucherJn { get; set; }
        public bool? AtemProblemeJn { get; set; }
        public string AtemProbleme { get; set; }
        public DateTime? AtemProblemeSeit { get; set; }
        public int? AtemProblemeAuftretung { get; set; }
        public string SonstigeAtemProblemeAuftretung { get; set; }
        public string AtemProblemeHilfeMassnahmenHilfsMittel { get; set; }
        public int? Tracheostoma { get; set; }
        public string TracheostomaBeschreibung { get; set; }
        public string BeobachtungenAtemProbleme { get; set; }
        public bool? FluessigkeitsproblemeJn { get; set; }
        public string Fluessigkeitsprobleme { get; set; }
        public DateTime? FluessigkeitsproblemeSeit { get; set; }
        public int? Durstgefuehl { get; set; }
        public double? Trinkmenge { get; set; }
        public string ZungeAussehen { get; set; }
        public string Trinkhilfen { get; set; }
        public string Hautturgor { get; set; }
        public string Oedeme { get; set; }
        public string BeobachtungFluessigkeitsprobleme { get; set; }
        public bool? ErnaehrungProblemeJn { get; set; }
        public string ErnaehrungProbleme { get; set; }
        public DateTime? ErnaehrungProblemeSeit { get; set; }
        public string Diaet { get; set; }
        public DateTime? DiaetSeit { get; set; }
        public string Essgewohnheiten { get; set; }
        public string ZahnKieferzustand { get; set; }
        public string MundschleimhautZustand { get; set; }
        public int? ErnaehrungParenteralEnteral { get; set; }
        public string ErnaehrungArt { get; set; }
        public DateTime? GelegtAm { get; set; }
        public string Stillgewohnheiten { get; set; }
        public string BeobachtungErnaehrungProbleme { get; set; }
        public bool? StuhlgangProblemeJn { get; set; }
        public string StuhlgangProbleme { get; set; }
        public DateTime? StuhlgangProblemeSeit { get; set; }
        public DateTime? LetzterStuhlAm { get; set; }
        public string StuhlgangAuffaelligkeitenVeraenderungBezHaeufigkeit { get; set; }
        public string StuhlgangAuffaelligkeitenVeraenderungBezFarbe { get; set; }
        public string StuhlgangAuffaelligkeitenVeraenderungBezKonsistenz { get; set; }
        public string StuhlgangAuffaelligkeitenVeraenderungBezMenge { get; set; }
        public string StuhlgangAuffaelligkeitenVeraenderungBezGeruch { get; set; }
        public string Abfuehrhilfen { get; set; }
        public string KuenstlicheAusgang { get; set; }
        public DateTime? KuenstlicheAusgangSeit { get; set; }
        public string StuhlgangBesondereGewohnheiten { get; set; }
        public string BeobachtungenStuhlgangProbleme { get; set; }
        public bool? UrinausscheidungProblemeJn { get; set; }
        public string UrinausscheidungProbleme { get; set; }
        public DateTime? UrinausscheidungProblemeSeit { get; set; }
        public int? UrinAuffaelligkeitenVeraenderungBezHaeufigkeitTagsueber { get; set; }
        public int? UrinAuffaelligkeitenVeraenderungBezHaeufigkeitTagsueberZeitabstand { get; set; }
        public int? UrinAuffaelligkeitenVeraenderungBezHaeufigkeitNachts { get; set; }
        public int? UrinAuffaelligkeitenVeraenderungBezHaeufigkeitNachtsZeitabstand { get; set; }
        public string UrinAuffaelligkeitenVeraenderungBezMenge { get; set; }
        public string UrinAuffaelligkeitenVeraenderungBezFarbe { get; set; }
        public string UrinAuffaelligkeitenVeraenderungBezGeruch { get; set; }
        public string HarnableitungssystemArt { get; set; }
        public DateTime? HarnableitungssystemGelegtAm { get; set; }
        public int? HarnableitungssystemGrosse { get; set; }
        public string BeobachtungenUrinausscheidungProbleme { get; set; }
        public bool? HautProblemeJn { get; set; }
        public string HautProbleme { get; set; }
        public bool? AussclagartigeHautveraendJn { get; set; }
        public string AussclagartigeHautveraendIn { get; set; }
        public string AussclagartigeHautveraend { get; set; }
        public bool? IntertrigoJn { get; set; }
        public string IntertrigoIn { get; set; }
        public string Intertrigo { get; set; }
        public bool? HaematomaPetechienBlutungenJn { get; set; }
        public string HaematomaPetechienBlutungenIn { get; set; }
        public string HaematomaPetechienBlutungen { get; set; }
        public bool? AnderWundenHautlaesionenJn { get; set; }
        public string AnderWundenHautlaesionenIn { get; set; }
        public string AnderWundenHautlaesionen { get; set; }
        public string Decubitus { get; set; }
        public int? Schweisssekretion { get; set; }
        public int? SchweissHaeufigkeit { get; set; }
        public string SchweissBesonderheiten { get; set; }
        public string BeobachtungenAusscheidung { get; set; }
        public bool? SichBewegenProblemeJn { get; set; }
        public string SichBewegenProbleme { get; set; }
        public DateTime? SichBewegenProblemeSeit { get; set; }
        public string BeobachtungenSichBewegen { get; set; }
        public int? BewegungImBett { get; set; }
        public string BewegungImBettBeschreibung { get; set; }
        public int? TransferBettAussehalb { get; set; }
        public string TransferBettAussehalbBeschreibung { get; set; }
        public int? MobilImRollstuhl { get; set; }
        public string MobilImRollstuhlBeschreibung { get; set; }
        public int? FortbewegungZuFuss { get; set; }
        public string FortbewegungZuFussBeschreibung { get; set; }
        public string BeobachtungSichBewegen { get; set; }
        public string RueckenmarklaesionProbleme { get; set; }
        public int? EssenTrinken { get; set; }
        public string EssenTrinkenBeschreibung { get; set; }
        public int? Koerperpflage { get; set; }
        public string KoerperpflageBeschreibung { get; set; }
        public int? Kleiden { get; set; }
        public string KleidenBeschreibung { get; set; }
        public int? SelbstpflageHarnTag { get; set; }
        public int? SelbstpflageHarnNacht { get; set; }
        public int? SelbstpflageStuhlTag { get; set; }
        public int? SelbstpflageStuhlNacht { get; set; }
        public string SelbstpflagedefizitBeschreibung { get; set; }
        public int? Haushalt { get; set; }
        public string HaushaltBeschreibung { get; set; }
        public int? Freizeit { get; set; }
        public string FreizeitBerschreibung { get; set; }
        public string SelbstpflagedefizitGewohnheiten { get; set; }
        public string BeobachtungenSelbstpflagedefizit { get; set; }
        public bool? SchlafproblemeJn { get; set; }
        public string Schlafprobleme { get; set; }
        public DateTime? SchlafproblemeSeit { get; set; }
        public string BeobachtungenSchlafprobleme { get; set; }
        public bool? KommunikationProblemeJn { get; set; }
        public string KommunikationProbleme { get; set; }
        public string KommunikationSelbsthilfe { get; set; }
        public string BeobachtungenKommunikationProbleme { get; set; }
        public string FamBeziehSozialeSituation { get; set; }
        public bool? FamBeziehSozialeProblemeJn { get; set; }
        public string FamBeziehSozialeProbleme { get; set; }
        public string Bezugsperson { get; set; }
        public bool? AbhaengigePersonenJn { get; set; }
        public string AbhaengigePersonen { get; set; }
        public bool? ZuHauseAllesRegelnKoennenJn { get; set; }
        public string ZuHauseNichtRegelnKoennen { get; set; }
        public string Besuchswuensche { get; set; }
        public string Situationsauswirkung { get; set; }
        public string BeobachtungenSozialesituation { get; set; }
        public bool? HinweiseKoerpPsychGewalteinwirkungenJn { get; set; }
        public string HinweiseKoerpPsychGewalteinwirkungen { get; set; }
        public string EinschneidendeLebenssituationsveraenderungen { get; set; }
        public string Suizidversuche { get; set; }
        public string BeobachtungenGewalteinwirkungen { get; set; }
        public string Sexualitaet { get; set; }
        public string BeobachtungenSexualitaet { get; set; }
        public bool? InfektionsgefahrJn { get; set; }
        public string Infektionsgefahr { get; set; }
        public bool? KoerperTempGefaehrdungJn { get; set; }
        public bool? KoerperTempVeraendertJn { get; set; }
        public int? KoerperTempVeraenderung { get; set; }
        public double? KoerperTemp { get; set; }
        public DateTime? KoerperTempVeraenderungSeit { get; set; }
        public string BeobachtungenKoerperTemp { get; set; }
        public bool? VorVerletzSturzKrankheitVergiftungSelbstSchuetzenJn { get; set; }
        public string BeobachtungenVorVerletzugen { get; set; }
        public bool? ErstickenErhoehtesRisikoJn { get; set; }
        public string BeobachtungenErsticken { get; set; }
        public bool? FluessigkeitenNahrungAspirationsrisikoJn { get; set; }
        public string BeobachtungenAspirationsrisiko { get; set; }
        public bool? KannBehandlungsprogrammAkzeptierenJn { get; set; }
        public string BeobachtungenBehandlungsprogramm { get; set; }
        public bool? ErkenntGesungheitsfoerdendeMassnahmenJn { get; set; }
        public string GesungheitsfoerdendeMassnahmen { get; set; }
        public string BeobachtungenGesungheitsfoerdendeMassnahmen { get; set; }
        public bool? BlutzirkulationStoerungenJn { get; set; }
        public string BlutzirkulationStoerungen { get; set; }
        public string BeobachtungenBlutzirkulation { get; set; }
        public bool? SchmerzenJn { get; set; }
        public string SchmerzenLokalisation { get; set; }
        public DateTime? SchmerzenSeit { get; set; }
        public string SchmerzenHaeufigkeit { get; set; }
        public string SchmerzenArt { get; set; }
        public int? SchmerzenIntensitaet { get; set; }
        public string SchmerzenAustrahlung { get; set; }
        public string SchmerzausloesendeFaktoren { get; set; }
        public string SchmerzverstaerkendeFaktoren { get; set; }
        public string SchmerzlinderndeFaktoren { get; set; }
        public string BeobachtungenSchmerzen { get; set; }
        public bool? FaehigkeitGesundheitszustandUmzugehenJn { get; set; }
        public string FaehigkeitGesundheitszustandAngaben { get; set; }
        public string BeobachtungenFaehigkeitGesundheitszustand { get; set; }
        public bool? FaehigkeitVorhandeneRessourcenZuErkennenJn { get; set; }
        public string BeobachtungenFaehigkeitVorhandeneRessourcen { get; set; }
        public bool? AngehoerigeBetreuungskonzeptMiteinbeziehenJn { get; set; }
        public string BetreuungskonseptAngaben { get; set; }
        public bool? FaehigkeitEntscheidungenZuTreffenJn { get; set; }
        public string FaehigkeitEntscheidungenZuTreffenAngaben { get; set; }
        public bool? FaehigkeitLebensanforderungenBegegnenZuKoennenJn { get; set; }
        public string BeobachtungenLebensanforderungen { get; set; }
        public bool? MoeglichkeitUmgebungsveraenderungAnzupassenJn { get; set; }
        public string BeobachtungenUmgebungsveraenderung { get; set; }
        public bool? EigeneKoerperAkzeptanzJn { get; set; }
        public string EigeneKoerperAkzeptanzAngaben { get; set; }
        public int? EigenPersonFaehigkeitenWertschaetzungen { get; set; }
        public string BeobachtungenEigenPersonFaehigkeitenWertschaetzungen { get; set; }
        public string UmfeldRealitaetsbezug { get; set; }
        public bool? SinneswahrnehmungUngestoertJn { get; set; }
        public string Sinneswahrnehmung { get; set; }
        public string SinneswahrnehmungSonstigeAngaben { get; set; }
        public string AeusserungenVonVerzweiflungVeraenderteLebensenergien { get; set; }
        public string BeobachtungenVeraenderteLebensenergien { get; set; }
        public bool? KannInfoZurSituationUmsetzenJn { get; set; }
        public string BeobachtungenInfoZurSituationUmsetzen { get; set; }
        public bool? FaehigkeitGedankenRichtigZuVerarbeitenJn { get; set; }
        public string BeobachtungenGedankenRichtigZuVerarbeiten { get; set; }
        public bool? BemerkbareTrauerreaktionJn { get; set; }
        public string BemerkbareTrauerreaktion { get; set; }
        public bool? HinweiseVermehrteBeschaeftigungMitSeelischeTraumaJn { get; set; }
        public string HinweiseVermehrteBeschaeftigung { get; set; }
        public bool? AngstzustaendeJn { get; set; }
        public string Angstzustaende { get; set; }
        public bool? SituationVorDerSichFuerchtenJn { get; set; }
        public string SituationVorDerSichFuerchten { get; set; }
        public string PflegendenAngehoerigeProbleme { get; set; }
        public int? Groesse { get; set; }
        public double? Gewicht { get; set; }
        public string Konfision { get; set; }
        public bool? ZahnersatzOkjn { get; set; }
        public bool? ZahnersatzUkjn { get; set; }
        public bool? SehhilfeBrilleJn { get; set; }
        public bool? SehhilfeKontaktlinsenJn { get; set; }
        public bool? HoergeraetRechtsJn { get; set; }
        public bool? HoergeraetLinksJn { get; set; }

        public virtual Benutzer IdbenutzerErstelltNavigation { get; set; }
        public virtual Patient IdpatientNavigation { get; set; }
        public virtual ICollection<Pdxanamnese> Pdxanamnese { get; set; }
    }
}