using System;
using System.Collections.Generic;

namespace WCFServicePMDS.Models.DB
{
    public partial class AnamneseKrohwinkel
    {
        public AnamneseKrohwinkel()
        {
            Pdxanamnese = new HashSet<Pdxanamnese>();
        }

        public Guid Id { get; set; }
        public Guid Idpatient { get; set; }
        public Guid? Idbenutzer { get; set; }
        public DateTime? ErstelltAm { get; set; }
        public bool? BrilleJn { get; set; }
        public bool? HoergeraetJn { get; set; }
        public bool? KannMitteilenJn { get; set; }
        public int? KommunizierenTagesstuktur { get; set; }
        public int? KommunizierenPflegeplanung { get; set; }
        public string Wuensche { get; set; }
        public int? SchwerhoerigTaubStummBlind { get; set; }
        public int? HoergeraetNichtHandhaben { get; set; }
        public int? Sprachstoerungen { get; set; }
        public int? Sichtfeldeinschraenkungen { get; set; }
        public int? IstZeitloertlSituativZurPersonNichtOrientiert { get; set; }
        public bool? KannSelbstBewegenJn { get; set; }
        public bool? GehentJn { get; set; }
        public bool? StehenJn { get; set; }
        public bool? SitzenJn { get; set; }
        public bool? TreppenSteigenJn { get; set; }
        public bool? LaufenJn { get; set; }
        public bool? HinsetzenJn { get; set; }
        public bool? HinlegenJn { get; set; }
        public bool? HilfsmittelBenutzenJn { get; set; }
        public bool? SpatzierenGehenJn { get; set; }
        public string WannWieOftSpatzieren { get; set; }
        public bool? KoerperlicheaktivitaetenJn { get; set; }
        public string AktivitaetenBeschreibung { get; set; }
        public bool? BewegenTagesstrukturJn { get; set; }
        public bool? BewegenPflegeplanung { get; set; }
        public bool? KontrakturenvorhandenJn { get; set; }
        public bool? SpitzfussstellungJn { get; set; }
        public bool? MaxGebEllenbogenJn { get; set; }
        public bool? KniegelenkJn { get; set; }
        public bool? GefausteteHandJn { get; set; }
        public string KontrakturenBeschreibung { get; set; }
        public bool? DekubitusVorhandenJn { get; set; }
        public string DekubitusBeschreibung { get; set; }
        public bool? SturtzgefahrJn { get; set; }
        public int? Bewegungseinschraenkung { get; set; }
        public int? KannNichtAlleinGehen { get; set; }
        public int? KannNichtAlleinLageImBettVeraendern { get; set; }
        public int? IstBettlaegerig { get; set; }
        public int? TransferAufstehenHinlegen { get; set; }
        public bool? BlutdruckZuckerRegelmaessigGemessenJn { get; set; }
        public bool? KompressionsstruempfeJn { get; set; }
        public int? Zimmertemperatur { get; set; }
        public bool? MedikamenteRegelmaessigJn { get; set; }
        public string Medikamente { get; set; }
        public bool? VitaleFunkTagesstrukturJn { get; set; }
        public bool? VitaleFunkPflegeplanungJn { get; set; }
        public int? ErhoehteErnidriegteBlutdruck { get; set; }
        public int? Durchblutungsstoerungen { get; set; }
        public int? FriertLeicht { get; set; }
        public int? DiabetesUnterUeberZucker { get; set; }
        public int? Sauerstoffmangel { get; set; }
        public int? BronchialsekretSchlechtAbhusten { get; set; }
        public int? StarkeAuswurf { get; set; }
        public int? AtemnotleichterAnstrengung { get; set; }
        public int? HilfeMedikamentenversorgung { get; set; }
        public string WieHandhabenMitDuschenBaden { get; set; }
        public string Koerperpflegemittel { get; set; }
        public string KoerperpflegemittelVersorger { get; set; }
        public string Rasieren { get; set; }
        public string Haarpflege { get; set; }
        public bool? ZahnFusspflegeHilfeJn { get; set; }
        public bool? SchminkenJn { get; set; }
        public bool? SichPflegenTagesstrukturJn { get; set; }
        public bool? SichPflegenPflegeplanungJn { get; set; }
        public int? HilfebWaschenDuschenBaden { get; set; }
        public int? HilfebHaareOberUnterkoerper { get; set; }
        public int? HilfebRasur { get; set; }
        public int? HilfebFussFingernagelpflege { get; set; }
        public int? HilfebIntimpflege { get; set; }
        public int? HilfebHautGesichtspflege { get; set; }
        public int? HilfebOhrenNasenAugenpflege { get; set; }
        public int? HilfebMundZahnpflege { get; set; }
        public int? HilfebHautdefekte { get; set; }
        public int? Starkschwitzen { get; set; }
        public string SpeisenGetraenke { get; set; }
        public string SpeisenGetraenkeAblehnen { get; set; }
        public double? AnzahlLiterTrinken { get; set; }
        public bool? MahlzeitInDerGemeinschaftJn { get; set; }
        public string FruehstueckSpaetFruehEinnehmen { get; set; }
        public string DiatSchonkostSondenernaehrung { get; set; }
        public int? AnzahlMalzeiten { get; set; }
        public bool? EssenTrinkenTagesstrukturJn { get; set; }
        public bool? EssenTrinkenPflegeplanungJn { get; set; }
        public int? NotwendigkeitEsssenTrinken { get; set; }
        public int? NotwendigkeitDiaet { get; set; }
        public int? KauSchluckstoerungen { get; set; }
        public int? IsstSehrlangsamm { get; set; }
        public int? NahrungMundgerechtZubereiten { get; set; }
        public int? MahlzeiteinnahmeHilfestellung { get; set; }
        public int? SondePegkomplett { get; set; }
        public int? SondenernaehrungKombinationmitOralerFluessigkeitsaufnahme { get; set; }
        public int? UnterstuezungUeberwachungFluessigkeitsaufnahme { get; set; }
        public int? HaufigErbrechen { get; set; }
        public bool? KannBlaseDarmKontrollierenJn { get; set; }
        public string ZeitenToiletteAufsuchen { get; set; }
        public bool? ToilettengangHilfeJn { get; set; }
        public string ToilettenHilfsmittel { get; set; }
        public string MedikamenteBlasenDarmfunktion { get; set; }
        public bool? AusscheidenTagesstrukturJn { get; set; }
        public bool? AusscheidenPflegeplanungJn { get; set; }
        public int? IstZeitweiseUrinStuhlinkontinent { get; set; }
        public int? UrinStuhlKrankheit { get; set; }
        public int? ZeitlUrinStuhlKrankheit { get; set; }
        public int? VerstopfungenDurchfaellen { get; set; }
        public int? VerstopfungDurchfallKrakheit { get; set; }
        public int? ZeitlVerstopfungDurchfallKrakheit { get; set; }
        public int? DauerSuprapubischenkatheter { get; set; }
        public int? NeigtZuInfektionen { get; set; }
        public int? HatAnusPraeter { get; set; }
        public int? KannToiletteNichtSelbstaendigBenutzen { get; set; }
        public int? UnterstuetzungEinnahmeAbfuehrmittel { get; set; }
        public string Kleidung { get; set; }
        public string Waeschewechsel { get; set; }
        public bool? SichKleidenTagesstrukturJn { get; set; }
        public bool? SichKleidenPflegeplanungJn { get; set; }
        public int? KleiderauswahlHilfe { get; set; }
        public int? WegenDesoriontiertheitOefterAusziehen { get; set; }
        public int? FehlendeEinsichtFuerAngemesseneKleidung { get; set; }
        public int? FehlendeEinsichtFuerNotwendigeWaeschewechsel { get; set; }
        public int? KannVerschluesseNichtHandhaben { get; set; }
        public int? KannNichtKleidungUeberKopfAusziehen { get; set; }
        public int? KannNichtKleidungUeberFusseAnziehen { get; set; }
        public string SchlafenVonBis { get; set; }
        public bool? MittagsschlafJn { get; set; }
        public bool? NachtsNachschauenJn { get; set; }
        public string SchlafBesonderheiten { get; set; }
        public string SchlafMedikamente { get; set; }
        public string SchlafGewohnheiten { get; set; }
        public bool? SchlafTagesstrukturJn { get; set; }
        public bool? SchlafPflegeplanungJn { get; set; }
        public int? HateinschlafDurchschlafstoerungen { get; set; }
        public int? HatPsychischeKrankheitsbedingteSchlafstoerungen { get; set; }
        public int? HatGestoertenTagNachtrhytmus { get; set; }
        public string Beruf { get; set; }
        public string GerneBeschaeftigtMit { get; set; }
        public string Tagsablauf { get; set; }
        public bool? TagesablaufsgestaltungHilfeJn { get; set; }
        public string TagesablaufsgestaltungHilfe { get; set; }
        public bool? SichBeschaeftigenTagesstrukturJn { get; set; }
        public bool? SichBeschaeftigenPflegeplanungJn { get; set; }
        public int? TagesablaufNachFrueherenGewohnheiten { get; set; }
        public int? ZeitpunktAufstehenBettGehenAbstimmen { get; set; }
        public int? IntegrationInTaeglicheAblaufe { get; set; }
        public string MaennlicheWeiblichePflegeperson { get; set; }
        public string MakeUpSchmuck { get; set; }
        public string HaarBarttracht { get; set; }
        public bool? SichFuehlenTagesstrukturJn { get; set; }
        public bool? SichFuehlenpflegeplanungJn { get; set; }
        public int? SchagefuehlIntimepflegeBeruecksichtigen { get; set; }
        public int? WuenschtMaennlicheWeiblicheBestimmtePflegeperson { get; set; }
        public int? KannFrisurNichtSelbstHerrichten { get; set; }
        public int? KannSchmuckNichtSelbstAnlegen { get; set; }
        public bool? HilfsmittelZurMobilitaetJn { get; set; }
        public bool? BettgitterJn { get; set; }
        public string ZimmerVerschlossen { get; set; }
        public bool? HilfeHerbeirufenJn { get; set; }
        public bool? OhneHilfeZurechtJn { get; set; }
        public bool? UmgebungTagesstrukturJn { get; set; }
        public bool? UmgebungPflegeplanungJn { get; set; }
        public int? KannGefahrenNichtEinschaetzen { get; set; }
        public int? InDerEinrichtungVerirrn { get; set; }
        public int? Sicherheit { get; set; }
        public int? MedikamenteneinnahmeUeberwachen { get; set; }
        public string Kontakte { get; set; }
        public string Keinekontakte { get; set; }
        public string ZeitKeineBesuche { get; set; }
        public string AndereKontakte { get; set; }
        public bool? KontakteSelbsstaendigHerstellenJn { get; set; }
        public bool? SozialeTagesstrukturJn { get; set; }
        public bool? SozialePflegeplanungJn { get; set; }
        public int? BewohnerBenoetigtAktivierung { get; set; }
        public int? HilfeBeiDerKontakpflege { get; set; }
        public int? InBetreuungImHausIntegrieren { get; set; }
        public string SterbephaseBetreuung { get; set; }
        public string Versorger { get; set; }
        public bool? ErfahrungenTagesstrukturJn { get; set; }
        public bool? ErfahrungenPflegeplanungJn { get; set; }
        public int? KannKrankheitBehinderungNichtAkzeptieren { get; set; }
        public int? LeidetAnVerlust { get; set; }
        public string LeidetAnVerlustVon { get; set; }
        public int? IstMisstraurisch { get; set; }
        public string IstMisstraurischGegen { get; set; }
        public int? HatSchmerzen { get; set; }
        public string Schmerzen { get; set; }
        public int? HatAngst { get; set; }
        public string AngstVon { get; set; }
        public string Biographie { get; set; }
        public bool? BiographieTagesstrukturJn { get; set; }
        public bool? BiographiePflegeplanungJn { get; set; }
        public int? UnbewaeltigtenLebenserfahrungen { get; set; }
        public int? Vermisst { get; set; }
        public string VermisstBeschreibung { get; set; }
        public int? HatSorge { get; set; }
        public string SorgeUm { get; set; }

        public virtual ICollection<Pdxanamnese> Pdxanamnese { get; set; }
    }
}