// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace WCFServicePMDS.Models.DB
{
    public partial class Pflegemodelle
    {
        public Pflegemodelle()
        {
            Pdxpflegemodelle = new HashSet<Pdxpflegemodelle>();
        }

        public Guid Id { get; set; }
        public string Modell { get; set; }
        public string ModellgruppeKlartext { get; set; }
        public int Modellgruppe { get; set; }
        public int Reihenfolge { get; set; }
        public string TemplateId { get; set; }
        public string TemplateId2 { get; set; }
        public string Code { get; set; }
        public string DisplayName { get; set; }
        public string CodeSystem { get; set; }
        public string CodeSystemName { get; set; }
        public string Title { get; set; }

        public virtual ICollection<Pdxpflegemodelle> Pdxpflegemodelle { get; set; }
    }
}